# Generated by Django 3.2.5 on 2021-09-27 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(max_length=100)),
                ('descripton', models.TextField(blank=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: College Algebra', max_length=200)),
                ('number', models.CharField(help_text='Example: MATH 136', max_length=200)),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Learning_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_activity', models.CharField(max_length=100)),
                ('descripton', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=100)),
                ('top_level', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('assessments', models.ManyToManyField(blank=True, related_name='assessment_related', to='LearnObjPlanApp.Assessment')),
                ('children', models.ManyToManyField(blank=True, help_text='Are other requirements derived from this one? If so, put them here. If not, leave blank. If you input children, the system will automatically add parents when you save.', related_name='children_related', to='LearnObjPlanApp.Objective')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.course')),
                ('learning_activities', models.ManyToManyField(blank=True, related_name='learning_activities_related', to='LearnObjPlanApp.Learning_Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='objective',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_slug_objective'),
        ),
        migrations.AddConstraint(
            model_name='learning_activity',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_slug_learning_activity'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_slug_course'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_slug_assessment'),
        ),
    ]
