# Generated by Django 3.2.5 on 2021-09-02 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(max_length=100)),
                ('descripton', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: College Algebra', max_length=200)),
                ('number', models.CharField(help_text='Example: MATH 136', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Learning_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_activity', models.CharField(max_length=100)),
                ('descripton', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('assessments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.assessment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.course')),
                ('learning_activities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.learning_activity')),
                ('parents', models.ManyToManyField(blank=True, help_text='Is this requirement devirived different requirements? If so, put that requirement here. If not, leave blank. If you input parents, the system will automatically add childern when you save.', related_name='parents_related', to='LearnObjPlanApp.Objective')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
