# Generated by Django 3.2.5 on 2021-09-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnObjPlanApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='parents',
        ),
        migrations.AddField(
            model_name='objective',
            name='children',
            field=models.ManyToManyField(blank=True, help_text='Are other requirements derived from this one? If so, put them here. If not, leave blank. If you input children, the system will automatically add parents when you save.', related_name='children_related', to='LearnObjPlanApp.Objective'),
        ),
    ]
