# Generated by Django 3.2.5 on 2021-07-19 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnObjPlanApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='contentarea',
            name='origin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.origin'),
        ),
        migrations.AlterField(
            model_name='contentarea',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.contentarea'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='content_area',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.contentarea'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='origin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.origin'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.objective'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='source_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='origin',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='origin',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
