# Generated by Django 3.2.5 on 2021-09-02 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnObjPlanApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='children',
        ),
        migrations.AddField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learning_activity',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.user'),
            preserve_default=False,
        ),
    ]
