# Generated by Django 3.2.5 on 2021-08-30 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnObjPlanApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='assessments',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.assessment'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='learning_activities',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.learning_activity'),
        ),
    ]
