# Generated by Django 3.2.5 on 2021-07-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnObjPlanApp', '0002_auto_20210719_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarea',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.origin'),
        ),
        migrations.AlterField(
            model_name='contentarea',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.contentarea'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='content_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.contentarea'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.origin'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.objective'),
        ),
    ]
