# Generated by Django 3.2.6 on 2021-09-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnObjPlanApp', '0002_auto_20210913_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='assessments',
        ),
        migrations.AddField(
            model_name='objective',
            name='assessments',
            field=models.ManyToManyField(blank=True, to='LearnObjPlanApp.Assessment'),
        ),
        migrations.RemoveField(
            model_name='objective',
            name='learning_activities',
        ),
        migrations.AddField(
            model_name='objective',
            name='learning_activities',
            field=models.ManyToManyField(blank=True, to='LearnObjPlanApp.Learning_Activity'),
        ),
    ]
