# Generated by Django 3.2.5 on 2021-09-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnObjPlanApp', '0003_auto_20210922_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='top_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='objective',
            name='assessments',
            field=models.ManyToManyField(blank=True, related_name='assessment_related', to='LearnObjPlanApp.Assessment'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='learning_activities',
            field=models.ManyToManyField(blank=True, related_name='learning_activities_related', to='LearnObjPlanApp.Learning_Activity'),
        ),
    ]
