# Generated by Django 3.2.5 on 2021-07-19 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnObjPlanApp', '0004_auto_20210719_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='source_number',
        ),
        migrations.AddField(
            model_name='objective',
            name='origin_number',
            field=models.CharField(blank=True, help_text='The number for objective from the origin. Leave blank if there is no origin or the origin does not list a number.', max_length=200),
        ),
        migrations.AlterField(
            model_name='contentarea',
            name='origin',
            field=models.ForeignKey(blank=True, help_text='Where did this requirement come from? Common sources are syllabi, accreditors, or institutional objectives. Leave blank for children.', null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.origin'),
        ),
        migrations.AlterField(
            model_name='contentarea',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Is this requirement devirived from a different requirement? Ifso, put that requirement here. If not, leave blank.', null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.contentarea'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Example: College Algebra', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(help_text='Example: MATH 136', max_length=200),
        ),
        migrations.AlterField(
            model_name='objective',
            name='origin',
            field=models.ForeignKey(blank=True, help_text='Where did this requirement come from? Common sources are syllabi, accreditors, or institutional objectives. Leave blank for children.', null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.origin'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Is this requirement devirived from a different requirement? Ifso, put that requirement here. If not, leave blank.', null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.objective'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Shortened name or acryonym for origin.', max_length=200),
        ),
        migrations.AlterField(
            model_name='origin',
            name='url',
            field=models.URLField(blank=True, help_text='Webpage where the origin is found.'),
        ),
    ]
