# Generated by Django 3.2.5 on 2021-09-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnObjPlanApp', '0006_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_activity',
            name='slug',
            field=models.SlugField(default='temp_slug'),
            preserve_default=False,
        ),
    ]
