# Generated by Django 3.2.5 on 2021-07-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnObjPlanApp', '0006_auto_20210723_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='parent',
            field=models.ManyToManyField(blank=True, help_text='Is this requirement devirived from a different requirement? Ifso, put that requirement here. If not, leave blank.', to='LearnObjPlanApp.Objective'),
        ),
    ]
