# Generated by Django 3.2.5 on 2021-09-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnObjPlanApp', '0007_learning_activity_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='slug',
            field=models.SlugField(default='temp_slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='slug',
            field=models.SlugField(default='temp_slug'),
            preserve_default=False,
        ),
    ]
