# Generated by Django 3.2.5 on 2021-07-24 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnObjPlanApp', '0007_alter_objective_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='parent',
        ),
        migrations.AddField(
            model_name='objective',
            name='children',
            field=models.ManyToManyField(blank=True, help_text='Are other requirements derived from this one? If so, put them here. If not, leave blank', related_name='children_related', to='LearnObjPlanApp.Objective'),
        ),
        migrations.AddField(
            model_name='objective',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='Is this requirement devirived different requirements? If so, put that requirement here. If not, leave blank.', related_name='parents_related', to='LearnObjPlanApp.Objective'),
        ),
        migrations.AlterField(
            model_name='contentarea',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Is this requirement devirived different requirements? If so, put that requirement here. If not, leave blank.', null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnObjPlanApp.contentarea'),
        ),
    ]
