# Generated by Django 3.2.5 on 2021-09-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnObjPlanApp', '0008_auto_20210922_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='learning_activity',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
